services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - portal
      - mail
      - api

#após a finalização do Compoose, dar um compose up --build
#tentar acessar http://localhost/portal
#http://localhost/webmail
#http://localhost/api